### ISSUE TITLE
RCPSPSolution.standardised_permutation not totally deterministic

### ISSUE THREAD

**Issue by nhuet** [airbus/discrete-optimization#125]
`standardised_permutation` attribute is meant to be unique for a given schedule in order to compare solutions based on it.
But is task are starting at the same time, the order between tasks is not guaranteed because it depends of the dictionary rcpsp_schedule keys ordering.

**Comment by g-poveda** [comment]
This is a limitation of the permutation encoding of solution, i don't think there is a really satisfying mitigation, thanks for notice
